### ISSUE TITLE
Usage of your sfmlAudio binding

### ISSUE THREAD

**Issue by mgrojo** [fastrgv/RufasSok#2]
This is just to let you know, that as suggested https://github.com/raph-amiard/ada-soundio/issues/1#issuecomment-691365644 I'm using your SFML binding in our toy project https://github.com/jfuica/bingada to support audio in Windows. By the moment, it's only tested in Ubuntu Linux and works without problem. I've added a GPR file to use from ours.

I've copied it into our repository (no possible git submodule):
https://github.com/jfuica/bingada/tree/master/libs/sfmlAudio

If you would prefer other way to include or reference the code and authorship just let me know.

**Comment by fastrgv** [comment]
I'm glad if you find it helpful. Note that the SFML binding is not portable
to all linux distros but it works fine for Windows and OSX (which I just
added), with suitable compilation methods.

**Comment by mgrojo** [comment]
For Linux, I've left both options, [canberra-ada ](https://github.com/onox/canberra-ada) and sfml, plus a null implementation.

I plan to build now for Windows using SFML. I'll take a look to your compilation scripts. In my case, I'm using GPR files, which seem, after learning how to use them, more easy and portable between Windows and Linux.

**Comment by fastrgv** [comment]
I use that binding for several games that I created, and it is very
portable.  I want to clarify something I said. That sfml binding is very
portable even on linux. The only problem is when you compile on one version
of linux, the executable might not run on another linux distro, UNLESS you
recompile and relink on that other distro.

**Comment by mgrojo** [comment]
Ok, thanks. I'm using AppImage to solve that kind of problems. It's relatively easy and it'll work in all distributions with support for AppImage (maybe not if they are too old). You can download the result [here](https://github.com/jfuica/bingada/releases). And you can take a look to how it's done in the Makefile.

Update: I've successfully built bingada using SFML in Windows. Thanks again.

**Comment by fastrgv** [comment]
I tried to compile bingada on linux Mint and got several undefined
references like "ca_proplist_destroy".
To get that far, first I had to create a symbolic link:
ln -s libcanberra-ada.so libcanberra.so
and then I had to add this to the gpr file:

package Linker is
for Default_Switches ("Ada") use
(
"-L./libs/canberra-ada/build/lib"
);
end Linker;

Another question: according to the advertisement Appimage is supposed to
allow YOU to create an executable that I can run.
?Why did you not create a linux executable...i.e. why do I need to compile
at all?  ? Do you plan to in the future?

Also, I would be interested how you like my delivery method if you were to
try downloading & running, say, "rufaswap":
https://github.com/fastrgv/RufasSwap

With rufaswap I believe you will have an executable for both Windows and
Linux that run without YOU having to recompile.

Anyway, I am interested in your suggestions for eliminating the undefined
references above...
Thx

**Comment by mgrojo** [comment]
> I tried to compile bingada on linux Mint and got several undefined references like "ca_proplist_destroy".

That symbol is part of libcanberra (the original C library, not the Ada binding). You have two options, either you install libcanberra-dev as described in https://github.com/onox/canberra-ada in order to build canberra-ada; or you avoid the build dependency by removing the line `with "libs/canberra-ada/tools/canberra.gpr";` in bingada.gpr.

Having to delete those lines to avoid dependency on external libraries is what I don't know if could be better resolved using GPR files.

> To get that far, first I had to create a symbolic link: ln -s libcanberra-ada.so libcanberra.so and then I had to add this to the gpr file: package Linker is for Default_Switches ("Ada") use ( "-L./libs/canberra-ada/build/lib" ); end Linker; 

You are mistaking the original libcanberra library, which should be provided by Linux Mint and provides a C API, with libcanberra-ada, which is being generated from the canberra-ada repository and later used by the application. The original repository is generating a shared library; it could be a static library as well.

> Another question: according to the advertisement Appimage is supposed to allow YOU to create an executable that I can run. ?Why did you not create a linux executable...i.e. why do I need to compile at all? ? Do you plan to in the future?

No, if you only want to execute bingada you can use the appropiate asset from the linked release. You can download there a Windows program directory and the AppImage for Linux. This should probably be stated in the README, but there, I only had in mind developers wanting to build bingada themselves.

> Also, I would be interested how you like my delivery method if you were to try downloading & running, say, "rufaswap": https://github.com/fastrgv/RufasSwap With rufaswap I believe you will have an executable for both Windows and Linux that run without YOU having to recompile. Anyway, I am interested in your suggestions for eliminating the undefined references above... Thx

I'm tested it under Windows and I don't find any `rufaswap` executable for Windows. I only see `rufaswap_gnu` and `rufaswap_osx`, which seem respectively for GNU/Linux and for macOS. Wouldn't make more sense to have the source code directly in the repository and then, in the releases, provide different so-called assets for each operating system?

**Comment by mgrojo** [comment]
Oh, I see now the `rufaswap.exe`, but I'm having problems executing it; it's complaining about the sound. Let me sort it out.

**Comment by fastrgv** [comment]
the command should be:  ./binw32/rufaswap.exe

I understand.
Yes, I would like to try to avoid canberra...
?do you have an alternate version of q_sound.adb that does not use Canberra?
I suppose you might have one that uses sfml-audio?
Thx

**Comment by fastrgv** [comment]
I forgot to say I got bingada to compile fine without sound!

**Comment by mgrojo** [comment]
> 
> the command should be: ./binw32/rufaswap.exe I understand. Yes, I would like to try to avoid canberra... ?do you have an alternate version of q_sound.adb that does not use Canberra? I suppose you might have one that uses sfml-audio? Thx

Yes, you can choose the sound option from the command line:
`gprbuild -XSOUND_LIB=sfml bingada`

As argument for `-XSOUND_LIB` you can pass canberra (default), sfml or none. Everything should built fine provided that either:
-  you have both libcanberra-dev and libsfml-dev packages;
- or you have removed the `with` statements in `bingada.gpr` of the packages that you cannot provide.

In the case of Windows, removing the  `with`  for libcanberra is always necessary to build, because the library cannot be installed in Windows. As I said, having to edit the GPR file to build is what I'm not satisfied with.

**Comment by mgrojo** [comment]
> 
> the command should be: ./binw32/rufaswap.exe 

Thanks! I was able to execute it, but before seeing your answer, I did it copying data and pix directories inside binw32. This is way I think it's easier for users if you provide a compiled version for each OS which is ready to launch.

**Comment by mgrojo** [comment]
By the way, do you know this [binding to SFML](https://github.com/danva994/ASFML-1.6)?

I've recently found it and I think it's interesting to have a full binding to SFML. It has to be updated to SFML 2 which has a lot of changes, but for the Audio part, I've got the music example to build and work, so could be an option for our projects. Maybe there's not much benefit in changing, but it would be nice to have a complete and somewhat official Ada binding for SFML. I plan to continue working in the update to SFML 2, although there's much to do.

**Comment by fastrgv** [comment]
Yes, I have looked at that a while ago.  sfml2 is way better and much
different, and even so, it uses code that is "deprecated".  This precludes
"modern" OpenGL and that is a deal-breaker for me.  That is why I
"split-out" the Audio, since it does not interfere with modern OpenGL code.

**Comment by mgrojo** [comment]
Then an Ada binding to SFML should be made so you don't have to include the OpenGL bits. I think that regarding the original libraries, you can use each library in isolation, so that should be preserved in the binding. Moreover, if you say that OpenGL in SFML uses deprecated OpenGL functions, then the Ada binding should skip this part if the developer intends to use some Ada binding to OpenGL like yours or  [OpenGLAda](https://github.com/flyx/OpenGLAda)? Would linking libsfml-graphics break that scenario? Then that might be a serious problem.

I might be saying something dumb, because I'm not familiarized with OpenGL.

**Comment by fastrgv** [comment]
Sorry, I was very unclear before.  I use GLFW.  This is from glfw FAQs:
4.1 - How do I create an OpenGL 3.0+ context in GLFW?  The only OpenGL 3.x
and 4.x contexts currently supported by macOS are forward-compatible, core
profile contexts.
It turns out that sfml (except for the audio) does not support
forward-compatible, core profile contexts, due to usage of
OpenGL-deprecated functions.

Thus, for my own development, I cannot use all of SFML.  Note that
OpenGLAda uses GLFW too.  I have one application that fully embraces & uses
OpenGLAda:  RufasCube.
